development:
  adapter: postgresql
  database: letras_development
  pool: 5

test:
  adapter: postgresql
  database: letras_test
  pool: 5

production:
  adapter: postgresql
  database: letras_production
  pool: 100
  user: postgres
